apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: app-cfgmap
data:
  app.conf: |
   server {
    listen 80;
    root   /usr/share/nginx/html/.well-known/acme-challenge;
    location / {
      try_files $uri $uri/ /index.html$is_args$args;
      index  index.html index.htm;
      include  /etc/nginx/mime.types;
      add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
      }
   }
   